spring.datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: sa
    password: pass

spring.flyway:
    enabled: true
    locations: classpath:db/migration
    # url: jdbc:postgresql://localhost:5432/demo
    # user: sa
    # password: pass
    baseline-on-migrate: false
    out-of-order: true
    check-location: false

spring:
    server:
        port:8080
# context-path:/catalog



